routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;


Route::group(
    ['prefix' => LaravelLocalization::setLocale(), 'middleware' => ['localeSessionRedirect', 'localizationRedirect', 'localeViewPath']], function () {
    Route::namespace('Dashboard')->group(function () {
        /**
         ************** Hassan Routes ***************
         */
        Route::redirect('/', '/dashboard/home');
        Route::redirect('login', '/dashboard/login');

        Route::group(['prefix' => 'dashboard', 'as' => 'dashboard.'], function () {
            //Authincation Route [login - Logout]
            Route::get('login', 'LoginController@showLoginForm')->name('login');
            Route::post('login', 'LoginController@login')->name('login_post');
            Route::get('logout', 'LoginController@logout')->name('logout');

            // Organization select after login request
            Route::get('/login/organizations', 'LoginController@organization')->name('login.organization.index');
            Route::post('/login/organizations', 'LoginController@save')->name('login.organization.save');

            Route::get('/login/cities', 'LoginController@cities')->name('login.cities.index');
            Route::post('/login/cities', 'LoginController@save_cities')->name('login.cities.save');

            Route::get('/login/organizations/create', 'LoginController@create_organization')->name('login.organization.create');
            Route::post('/login/organizations/store', 'LoginController@store_organization')->name('login.organization.store');

            Route::group(['middleware' => 'organization'], function () {
                //Home page in Dashboard Route
                Route::get('/home', 'HomeController@index')->name('index');

                //Profile Routes
                Route::group(['prefix' => 'profile'], function () {
                    Route::get('/', 'ProfileController@index')->name('profile.index');
                    Route::post('/update', 'ProfileController@update')->name('profile.update');
                    Route::group(['prefix' => 'changePassword'], function () {
                        Route::get('/', 'ProfileController@changePassword')->name('profile.changePassword');
                        Route::post('/update', 'ProfileController@updatePassword')->name('profile.changePassword.update');
                    });
                });
            });
        });
    });
});

app/Http/Controllers/Dashboard/HomeController.php
<?php

namespace app\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\Bed;


class HomeController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $title = __('dashboard.home');

        $beds = Bed::where('organization_id',session('organization_id'))->inRandomOrder()->get();

        return view('dashboard.index', compact('beds','title'));
    }

}

app/Http/Controllers/Dashboard/LoginController.php
<?php

namespace app\Http\Controllers\Dashboard;

use App\Http\Requests\LoginRequest;
use App\Models\Bed;
use App\Models\City;
use App\Models\Organization;
use App\Models\User;
use Illuminate\Auth\Events\Login;
use Illuminate\Contracts\Auth\Factory;
use Illuminate\Contracts\Console\Application;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Routing\Redirector;
use Illuminate\Support\Facades\Auth;
use Illuminate\Validation\ValidationException;


class LoginController extends Controller
{
    /**
     * LoginController constructor.
     */
    public function __construct()
    {
       $this->middleware('auth')->only('logout','organization','save');
    }

    /**
     * @return View
     */
    public function showLoginForm(): View
    {
        return view('dashboard.login');
    }

    /**
     * @param LoginRequest $request
     * @return RedirectResponse
     * @throws ValidationException
     */
    public function login(LoginRequest $request): RedirectResponse
    {
        $credentials = $request->only('mobile', 'password');
        if (Auth::attempt($credentials,true)) {

            return redirect()->route('dashboard.login.cities.index');
        }

        throw ValidationException::withMessages([
            'mobile' => [trans('auth.failed')],
        ]);
    }

    /**
     * @return Application|Factory|View|RedirectResponse|Redirector
     */
    public function organization()
    {
        $title = trans('dashboard.organizations');
        $organizations = Organization::orderBy('id', 'DESC')
            ->where('city_id',session('city_id'))->get();

        return view('dashboard.organizations',compact('title','organizations'));
    }

    /**
     * @return Application|Factory|View|RedirectResponse|Redirector
     */
    public function cities()
    {
        $title = 'المحافظات';
        $cities = City::with('orgainzation')->get();

        return view('dashboard.cities',compact('title','cities'));
    }


    /**
     * @return View
     */
    public function create_organization(): View
    {
        $title = trans('dashboard.create_organization');
        $langs = ['ar' , 'en' ];

        return view('dashboard.create_organization',compact('title','langs'));
    }

    /**
     * @param Request $request
     * @return RedirectResponse
     */
    public function store_organization(Request $request): RedirectResponse
    {
        $request_data = $request->all();
        $request_data['city_id'] = session('city_id');

        $organization = Organization::create($request_data);

            for($i = 0; $i < $organization->number_beds_pending; $i++){
                Bed::create([
                    'type' =>'full',
                    'organization_id' => $organization->id
                ]);
            }
            for($i = 0; $i < $organization->number_beds_avaible; $i++){
                Bed::create([
                    'type' =>'empty',
                    'organization_id' =>  $organization->id
                ]);
            }


        session(['organization_id' => $organization->id]);

        return redirect(url('dashboard/home'))->with(
            ['status' => 'success', 'message' => trans('dashboard.organization_added_successfully')]
        );

    }

    /**
     * @param Request $request
     * @return RedirectResponse
     */
    public function save(Request $request): RedirectResponse
    {
        $request->validate(['organization_id' => 'required|numeric|exists:organizations,id']);

        session(['organization_id' => $request->organization_id]);

        return redirect()->route('dashboard.index');
    }

    /**
     * @param Request $request
     * @return RedirectResponse
     */
    public function save_cities(Request $request): RedirectResponse
    {
        $request->validate(['city_id' => 'required']);

        session(['city_id' => $request->city_id]);

        return redirect()->route('dashboard.login.organization.index');
    }

    /**
     * @param Request $request
     * @return RedirectResponse
     */
    public function logout(Request $request): RedirectResponse
    {
        Auth::logout();
        $request->session()->invalidate();
        session()->flush('organization_id');

        return redirect()->route('dashboard.login');
    }
}

resources/views/dashboard/profile/changePassword.blade.php
@extends('dashboard.profile.index')

@section('profile_header')
    <div class="subheader py-2 py-lg-6 subheader-transparent" id="kt_subheader">
        <div class="container-fluid d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
            <!--begin::Info-->
            <div class="d-flex align-items-center flex-wrap mr-1">
                <!--begin::Mobile Toggle-->
                <button class="burger-icon burger-icon-left mr-4 d-inline-block d-lg-none"
                        id="kt_subheader_mobile_toggle">
                    <span></span>
                </button>
                <!--end::Mobile Toggle-->
                <!--begin::Page Heading-->
                <div class="d-flex align-items-baseline flex-wrap mr-5">
                    <!--begin::Page Title-->
                    <h5 class="text-dark font-weight-bold my-1 mr-5">Profile 1</h5>
                    <!--end::Page Title-->
                    <!--begin::Breadcrumb-->
                    <ul class="breadcrumb breadcrumb-transparent breadcrumb-dot font-weight-bold p-0 my-2 font-size-sm">
                        <li class="breadcrumb-item">
                            <a href="" class="text-muted">Apps</a>
                        </li>
                        <li class="breadcrumb-item">
                            <a href="" class="text-muted">Profile</a>
                        </li>
                        <li class="breadcrumb-item">
                            <a href="" class="text-muted">Profile 1</a>
                        </li>
                        <li class="breadcrumb-item">
                            <a href="" class="text-muted">Change Password</a>
                        </li>
                    </ul>
                    <!--end::Breadcrumb-->
                </div>
                <!--end::Page Heading-->
            </div>
            <!--end::Info-->
            <!--begin::Toolbar-->
            <div class="d-flex align-items-center">
                <!--begin::Actions-->
                <a href="#" class="btn btn-light-primary font-weight-bolder btn-sm">Actions</a>
                <!--end::Actions-->
                <!--begin::Dropdown-->
                <div class="dropdown dropdown-inline" data-toggle="tooltip" title="Quick actions" data-placement="left">
                    <a href="#" class="btn btn-icon" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
											<span class="svg-icon svg-icon-success svg-icon-2x">
												<!--begin::Svg Icon | path:assets/media/svg/icons/Files/File-plus.svg-->
												<svg xmlns="http://www.w3.org/2000/svg"
                                                     xmlns:xlink="http://www.w3.org/1999/xlink" width="24px"
                                                     height="24px" viewBox="0 0 24 24" version="1.1">
													<g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
														<polygon points="0 0 24 0 24 24 0 24"/>
														<path
                                                            d="M5.85714286,2 L13.7364114,2 C14.0910962,2 14.4343066,2.12568431 14.7051108,2.35473959 L19.4686994,6.3839416 C19.8056532,6.66894833 20,7.08787823 20,7.52920201 L20,20.0833333 C20,21.8738751 19.9795521,22 18.1428571,22 L5.85714286,22 C4.02044787,22 4,21.8738751 4,20.0833333 L4,3.91666667 C4,2.12612489 4.02044787,2 5.85714286,2 Z"
                                                            fill="#000000" fill-rule="nonzero" opacity="0.3"/>
														<path
                                                            d="M11,14 L9,14 C8.44771525,14 8,13.5522847 8,13 C8,12.4477153 8.44771525,12 9,12 L11,12 L11,10 C11,9.44771525 11.4477153,9 12,9 C12.5522847,9 13,9.44771525 13,10 L13,12 L15,12 C15.5522847,12 16,12.4477153 16,13 C16,13.5522847 15.5522847,14 15,14 L13,14 L13,16 C13,16.5522847 12.5522847,17 12,17 C11.4477153,17 11,16.5522847 11,16 L11,14 Z"
                                                            fill="#000000"/>
													</g>
												</svg>
                                                <!--end::Svg Icon-->
											</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-md dropdown-menu-right p-0 m-0">
                        <!--begin::Navigation-->
                        <ul class="navi navi-hover">
                            <li class="navi-header font-weight-bold py-4">
                                <span class="font-size-lg">Choose Label:</span>
                                <i class="flaticon2-information icon-md text-muted" data-toggle="tooltip"
                                   data-placement="right" title="Click to learn more..."></i>
                            </li>
                            <li class="navi-separator mb-3 opacity-70"></li>
                            <li class="navi-item">
                                <a href="#" class="navi-link">
														<span class="navi-text">
															<span
                                                                class="label label-xl label-inline label-light-success">Customer</span>
														</span>
                                </a>
                            </li>
                            <li class="navi-item">
                                <a href="#" class="navi-link">
														<span class="navi-text">
															<span
                                                                class="label label-xl label-inline label-light-danger">Partner</span>
														</span>
                                </a>
                            </li>
                            <li class="navi-item">
                                <a href="#" class="navi-link">
														<span class="navi-text">
															<span
                                                                class="label label-xl label-inline label-light-warning">Suplier</span>
														</span>
                                </a>
                            </li>
                            <li class="navi-item">
                                <a href="#" class="navi-link">
														<span class="navi-text">
															<span
                                                                class="label label-xl label-inline label-light-primary">Member</span>
														</span>
                                </a>
                            </li>
                            <li class="navi-item">
                                <a href="#" class="navi-link">
														<span class="navi-text">
															<span class="label label-xl label-inline label-light-dark">Staff</span>
														</span>
                                </a>
                            </li>
                            <li class="navi-separator mt-3 opacity-70"></li>
                            <li class="navi-footer py-4">
                                <a class="btn btn-clean font-weight-bold btn-sm" href="#">
                                    <i class="ki ki-plus icon-sm"></i>Add new</a>
                            </li>
                        </ul>
                        <!--end::Navigation-->
                    </div>
                </div>
                <!--end::Dropdown-->
            </div>
            <!--end::Toolbar-->
        </div>
    </div>
@endsection
@section('profile_content')
    <div class="flex-row-fluid ml-lg-8">
        <!--begin::Card-->
        <div class="card card-custom">
            <!--begin::Header-->
            <form class="form" method="post" action="{{route('dashboard.profile.changePassword.update')}}">
                {{csrf_field()}}
                <div class="card-header py-3">
                    <div class="card-title align-items-start flex-column">
                        <h3 class="card-label font-weight-bolder text-dark">{{__('dashboard.change_password')}}</h3>
                    </div>
                    <div class="card-toolbar">
                        <button type="submit" class="btn btn-success mr-2">{{__('dashboard.save')}}</button>
                        <button type="reset" class="btn btn-secondary">{{__('dashboard.cancel')}}</button>
                    </div>
                </div>
                <!--end::Header-->
                <!--begin::Form-->
                <div class="card-body">
                    <div class="form-group row">
                        <label
                            class="col-xl-3 col-lg-3 col-form-label text-alert">{{__('dashboard.password')}}</label>
                        <div class="col-lg-9 col-xl-6">
                            <input type="password" name="password"
                                   class="form-control form-control-lg form-control-solid mb-2"
                                   placeholder="{{__('dashboard.enter')}} {{__('dashboard.password')}}"/>
                            <div class="text-danger">
                                <strong>{{ $errors->has('password') ? $errors->first('password') : '' }}</strong>
                            </div>
                        </div>

                    </div>
                    <div class="form-group row">
                        <label
                            class="col-xl-3 col-lg-3 col-form-label text-alert">{{__('dashboard.new_password')}}</label>
                        <div class="col-lg-9 col-xl-6">
                            <input type="password" class="form-control form-control-lg form-control-solid"
                                   name="new_password"
                                   placeholder="{{__('dashboard.enter')}} {{__('dashboard.new_password')}}"/>
                            <div class="text-danger">
                                <strong>{{ $errors->has('new_password') ? $errors->first('new_password') : '' }}</strong>
                            </div>
                        </div>

                    </div>
                    <div class="form-group row">
                        <label
                            class="col-xl-3 col-lg-3 col-form-label text-alert">{{__('dashboard.new_password_confirmation')}}</label>
                        <div class="col-lg-9 col-xl-6">
                            <input type="password" name="new_password_confirmation"
                                   class="form-control form-control-lg form-control-solid"
                                   placeholder="{{__('dashboard.enter')}} {{__('dashboard.new_password_confirmation')}}"/>
                            <div class="text-danger">
                                <strong>{{ $errors->has('new_password_confirmation') ? $errors->first('new_password_confirmation') : '' }}</strong>
                            </div>

                        </div>

                    </div>
                </div>
            </form>
            <!--end::Form-->
        </div>
    </div>
@endsection

resources/views/dashboard/profile/index.blade.php
@extends('dashboard.layouts.master')
@section('page_header')
    <div class="subheader py-2 py-lg-6 subheader-transparent" id="kt_subheader">
        <div class="container-fluid d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
            <div class="d-flex align-items-center flex-wrap mr-1">
                <div class="d-flex align-items-baseline flex-wrap mr-5">
                    <h5 class="text-dark font-weight-bold my-1 mr-5">{{__('dashboard.profile_info')}}</h5>
                    <ul class="breadcrumb breadcrumb-transparent breadcrumb-dot font-weight-bold p-0 my-2 font-size-sm">
                        <li class="breadcrumb-item">
                            <a href="" class="text-muted">{{Auth::user()->name??'-'}}</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('content')
    <div class="d-flex flex-column-fluid">
        <!--begin::Container-->
        <div class="container-fluid">
            <!--begin::Profile Personal Information-->
            <div class="d-flex flex-row">
                <!--begin::Aside-->
                <div class="flex-row-auto offcanvas-mobile w-250px w-xxl-350px" id="kt_profile_aside">
                    <!--begin::Profile Card-->
                    <div class="card card-custom card-stretch">
                        <!--begin::Body-->
                        <div class="card-body pt-4">
                            <!--begin::User-->
                            <div class="d-flex align-items-center">
                                <div
                                    class="symbol symbol-60 symbol-xxl-100 mr-5 align-self-start align-self-xxl-center">

                                    <div class="symbol-label"
                                         style="background-image:url('{{(Auth::user()->photo != null && Storage::disk('public')->exists(Auth::user()->photo) ) ? Storage::url(Auth::user()->photo):asset('dashboard/assets/media/users/blank.png')}}')"></div>
                                    <i class="symbol-badge bg-success"></i>
                                </div>
                                <div>
                                    <a href="#"
                                       class="font-weight-bolder font-size-h5 text-dark-75 text-hover-primary">{{Auth::user()->name??'-'}}</a>
                                    <div class="text-muted">{{__('dashboard.'.Auth::user()->type)}}</div>
                                </div>
                            </div>
                            <!--end::User-->
                            <!--begin::Contact-->
                            <div class="py-9">
                                <div class="d-flex align-items-center justify-content-between mb-2">
                                    <span class="font-weight-bold mr-2">{{__('dashboard.email')}}:</span>
                                    <a href="#" class="text-muted text-hover-primary">{{Auth::user()->email}}</a>
                                </div>
                                <div class="d-flex align-items-center justify-content-between mb-2">
                                    <span class="font-weight-bold mr-2">{{__('dashboard.mobile')}}:</span>
                                    <span class="text-muted">{{Auth::user()->mobile}}</span>
                                </div>
                            </div>
                            <!--end::Contact-->
                            <!--begin::Nav-->
                            <div class="navi navi-bold navi-hover navi-active navi-link-rounded">
                                <div class="navi-item mb-2">
                                    <a href="{{route('dashboard.profile.index')}}"
                                       class="navi-link py-4 {{ request()->is('*/profile') ? 'active' : '' }} ">
															<span class="navi-icon mr-2">
																<span class="svg-icon">
																	<!--begin::Svg Icon | path:assets/media/svg/icons/General/User.svg-->
																	<svg xmlns="http://www.w3.org/2000/svg"
                                                                         xmlns:xlink="http://www.w3.org/1999/xlink"
                                                                         width="24px" height="24px" viewBox="0 0 24 24"
                                                                         version="1.1">
																		<g stroke="none" stroke-width="1" fill="none"
                                                                           fill-rule="evenodd">
																			<polygon points="0 0 24 0 24 24 0 24"/>
																			<path
                                                                                d="M12,11 C9.790861,11 8,9.209139 8,7 C8,4.790861 9.790861,3 12,3 C14.209139,3 16,4.790861 16,7 C16,9.209139 14.209139,11 12,11 Z"
                                                                                fill="#000000" fill-rule="nonzero"
                                                                                opacity="0.3"/>
																			<path
                                                                                d="M3.00065168,20.1992055 C3.38825852,15.4265159 7.26191235,13 11.9833413,13 C16.7712164,13 20.7048837,15.2931929 20.9979143,20.2 C21.0095879,20.3954741 20.9979143,21 20.2466999,21 C16.541124,21 11.0347247,21 3.72750223,21 C3.47671215,21 2.97953825,20.45918 3.00065168,20.1992055 Z"
                                                                                fill="#000000" fill-rule="nonzero"/>
																		</g>
																	</svg>
                                                                    <!--end::Svg Icon-->
																</span>
															</span>
                                        <span
                                            class="navi-text font-size-lg">{{__('dashboard.personal_info')}}</span>
                                    </a>
                                </div>
                                <div class="navi-item mb-2 ">
                                    <a href="{{route('dashboard.profile.changePassword')}}"
                                       class="navi-link py-4 {{ request()->is('*/profile/changePassword') ? 'active' : '' }}">
                                        <span class="navi-icon mr-2">
                                            <span class="svg-icon">
                                                <!--begin::Svg Icon | path:assets/media/svg/icons/Communication/Shield-user.svg-->
                                                <svg xmlns="http://www.w3.org/2000/svg"
                                                     xmlns:xlink="http://www.w3.org/1999/xlink"
                                                     width="24px" height="24px" viewBox="0 0 24 24"
                                                     version="1.1">
                                                    <g stroke="none" stroke-width="1" fill="none"
                                                       fill-rule="evenodd">
                                                        <rect x="0" y="0" width="24" height="24"/>
                                                        <path
                                                            d="M4,4 L11.6314229,2.5691082 C11.8750185,2.52343403 12.1249815,2.52343403 12.3685771,2.5691082 L20,4 L20,13.2830094 C20,16.2173861 18.4883464,18.9447835 16,20.5 L12.5299989,22.6687507 C12.2057287,22.8714196 11.7942713,22.8714196 11.4700011,22.6687507 L8,20.5 C5.51165358,18.9447835 4,16.2173861 4,13.2830094 L4,4 Z"
                                                            fill="#000000" opacity="0.3"/>
                                                        <path
                                                            d="M12,11 C10.8954305,11 10,10.1045695 10,9 C10,7.8954305 10.8954305,7 12,7 C13.1045695,7 14,7.8954305 14,9 C14,10.1045695 13.1045695,11 12,11 Z"
                                                            fill="#000000" opacity="0.3"/>
                                                        <path
                                                            d="M7.00036205,16.4995035 C7.21569918,13.5165724 9.36772908,12 11.9907452,12 C14.6506758,12 16.8360465,13.4332455 16.9988413,16.5 C17.0053266,16.6221713 16.9988413,17 16.5815,17 C14.5228466,17 11.463736,17 7.4041679,17 C7.26484009,17 6.98863236,16.6619875 7.00036205,16.4995035 Z"
                                                            fill="#000000" opacity="0.3"/>
                                                    </g>
                                                </svg>
                                                <!--end::Svg Icon-->
                                            </span>
                                        </span>
                                        <span class="navi-text font-size-lg">{{__('dashboard.change_password')}}</span>
                                        <span class="navi-label"></span>
                                    </a>
                                </div>
                            </div>
                            <!--end::Nav-->
                        </div>
                        <!--end::Body-->
                    </div>
                    <!--end::Profile Card-->
                </div>
                <!--end::Aside-->
                <!--begin::Content-->
            @yield('profile_content')
            <!--end::Content-->
            </div>
            <!--end::Profile Personal Information-->
        </div>
        <!--end::Container-->
    </div>
@endsection
@push('script')
    <script src="{{asset('dashboard/assets/js/pages/custom/profile/profile.js')}}"></script>
@endpush