routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;


Route::group(
    ['prefix' => LaravelLocalization::setLocale(), 'middleware' => ['localeSessionRedirect', 'localizationRedirect', 'localeViewPath']], function () {
    Route::namespace('Dashboard')->group(function () {
        /**
         ************** Hassan Routes ***************
         */
        Route::redirect('/', '/dashboard/home');
        Route::redirect('login', '/dashboard/login');

        Route::group(['prefix' => 'dashboard', 'as' => 'dashboard.'], function () {
            //Authincation Route [login - Logout]
            Route::get('login', 'LoginController@showLoginForm')->name('login');
            Route::post('login', 'LoginController@login')->name('login_post');
            Route::get('logout', 'LoginController@logout')->name('logout');

            // Organization select after login request
            Route::get('/login/organizations', 'LoginController@organization')->name('login.organization.index');
            Route::post('/login/organizations', 'LoginController@save')->name('login.organization.save');

            Route::get('/login/cities', 'LoginController@cities')->name('login.cities.index');
            Route::post('/login/cities', 'LoginController@save_cities')->name('login.cities.save');

            Route::get('/login/organizations/create', 'LoginController@create_organization')->name('login.organization.create');
            Route::post('/login/organizations/store', 'LoginController@store_organization')->name('login.organization.store');

            Route::group(['middleware' => 'organization'], function () {
                //Home page in Dashboard Route
                Route::get('/home', 'HomeController@index')->name('index');

                //Profile Routes
                Route::group(['prefix' => 'profile'], function () {
                    Route::get('/', 'ProfileController@index')->name('profile.index');
                    Route::post('/update', 'ProfileController@update')->name('profile.update');
                    Route::group(['prefix' => 'changePassword'], function () {
                        Route::get('/', 'ProfileController@changePassword')->name('profile.changePassword');
                        Route::post('/update', 'ProfileController@updatePassword')->name('profile.changePassword.update');
                    });
                });
            });
        });
    });
});

app/Http/Controllers/Dashboard/HomeController.php
<?php

namespace app\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\Bed;


class HomeController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $title = __('dashboard.home');

        $beds = Bed::where('organization_id',session('organization_id'))->inRandomOrder()->get();

        return view('dashboard.index', compact('beds','title'));
    }

}

app/Http/Controllers/Dashboard/LoginController.php
<?php

namespace app\Http\Controllers\Dashboard;

use App\Http\Requests\LoginRequest;
use App\Models\Bed;
use App\Models\City;
use App\Models\Organization;
use App\Models\User;
use Illuminate\Auth\Events\Login;
use Illuminate\Contracts\Auth\Factory;
use Illuminate\Contracts\Console\Application;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Routing\Redirector;
use Illuminate\Support\Facades\Auth;
use Illuminate\Validation\ValidationException;


class LoginController extends Controller
{
    /**
     * LoginController constructor.
     */
    public function __construct()
    {
       $this->middleware('auth')->only('logout','organization','save');
    }

    /**
     * @return View
     */
    public function showLoginForm(): View
    {
        return view('dashboard.login');
    }

    /**
     * @param LoginRequest $request
     * @return RedirectResponse
     * @throws ValidationException
     */
    public function login(LoginRequest $request): RedirectResponse
    {
        $credentials = $request->only('mobile', 'password');
        if (Auth::attempt($credentials,true)) {

            return redirect()->route('dashboard.login.cities.index');
        }

        throw ValidationException::withMessages([
            'mobile' => [trans('auth.failed')],
        ]);
    }

    /**
     * @return Application|Factory|View|RedirectResponse|Redirector
     */
    public function organization()
    {
        $title = trans('dashboard.organizations');
        $organizations = Organization::orderBy('id', 'DESC')
            ->where('city_id',session('city_id'))->get();

        return view('dashboard.organizations',compact('title','organizations'));
    }

    /**
     * @return Application|Factory|View|RedirectResponse|Redirector
     */
    public function cities()
    {
        $title = 'المحافظات';
        $cities = City::with('orgainzation')->get();

        return view('dashboard.cities',compact('title','cities'));
    }


    /**
     * @return View
     */
    public function create_organization(): View
    {
        $title = trans('dashboard.create_organization');
        $langs = ['ar' , 'en' ];

        return view('dashboard.create_organization',compact('title','langs'));
    }

    /**
     * @param Request $request
     * @return RedirectResponse
     */
    public function store_organization(Request $request): RedirectResponse
    {
        $request_data = $request->all();
        $request_data['city_id'] = session('city_id');

        $organization = Organization::create($request_data);

            for($i = 0; $i < $organization->number_beds_pending; $i++){
                Bed::create([
                    'type' =>'full',
                    'organization_id' => $organization->id
                ]);
            }
            for($i = 0; $i < $organization->number_beds_avaible; $i++){
                Bed::create([
                    'type' =>'empty',
                    'organization_id' =>  $organization->id
                ]);
            }


        session(['organization_id' => $organization->id]);

        return redirect(url('dashboard/home'))->with(
            ['status' => 'success', 'message' => trans('dashboard.organization_added_successfully')]
        );

    }

    /**
     * @param Request $request
     * @return RedirectResponse
     */
    public function save(Request $request): RedirectResponse
    {
        $request->validate(['organization_id' => 'required|numeric|exists:organizations,id']);

        session(['organization_id' => $request->organization_id]);

        return redirect()->route('dashboard.index');
    }

    /**
     * @param Request $request
     * @return RedirectResponse
     */
    public function save_cities(Request $request): RedirectResponse
    {
        $request->validate(['city_id' => 'required']);

        session(['city_id' => $request->city_id]);

        return redirect()->route('dashboard.login.organization.index');
    }

    /**
     * @param Request $request
     * @return RedirectResponse
     */
    public function logout(Request $request): RedirectResponse
    {
        Auth::logout();
        $request->session()->invalidate();
        session()->flush('organization_id');

        return redirect()->route('dashboard.login');
    }
}

resources/views/dashboard/cities.blade.php
@extends('dashboard.layouts.app')
@push('style')
    <link href="{{asset('dashboard/assets/css/pages/login/login-4.css')}}" rel="stylesheet" type="text/css"/>
@endpush
@section('page')
    <div class="d-flex flex-column-fluid">
        <div class="container">
            <a href="{{route('dashboard.logout')}}" type="submit"
               class="btn font-weight-bolder text-uppercase btn-danger py-4 px-6"
               style="float: left;margin-top: 22px;">
                <i class="flaticon-logout"></i>
                @lang('dashboard.logout')
            </a>
        <div  style="margin: 11% auto;">
            @if((!empty($cities->first())))
                <div class="row" style=" @if($cities->count() < 4) margin-top: 17% !important; @else margin-top: 4% !important; @endif">
                    @if(session()->has('status'))
                        @include('dashboard.includes.alerts',['message' => session()->get('message'),'alert_class' => session()->get('status')])
                    @endif
                    @foreach($cities as $city)
                        <div class="col-md-4" style="margin-bottom: 3%">
                        <div class="card card-custom">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="symbol symbol-120 symbol-2by3 flex-shrink-0">
                                            <div class="symbol-label" style="background-image: url({{Storage::disk('public')->exists($city->photo)?
                                               Storage::url($city->photo): asset('dashboard/assets/media/organization/default.png')
                                                }});  height: 150px">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div style="font-size: 14px !important;">
                                            <button type="button" class="btn btn-success font-weight-bold mr-1 mb-1 btn-sm">
                                                <span>عدد المسنفيات : <strong>{{$city->orgainzation->count()}}</strong><br></span>
                                            </button>
                                            <button type="button" class="btn btn-success font-weight-bold mr-1 mb-1 btn-sm">
                                                السراير المتاحة : <strong>{{$city->number_beds_avaible}}</strong><br>
                                            </button>
                                            <button type="button" class="btn btn-danger font-weight-bold mr-1 mb-1 btn-sm">
                                                السراير المشغولة : <strong>{{$city->number_beds_pending}}</strong>
                                            </button>
                                            <button type="button" class="btn btn-danger font-weight-bold mr-1 mb-1 btn-sm">
                                                السراير الكلية : <strong>{{$city->number_beds_total}}</strong>
                                            </button>
                                        </div>
                                    </div>
                                </div>

                                <div class="d-flex align-items-center justify-content-between p-4 flex-lg-wrap flex-xl-nowrap">
                                    <div class="d-flex flex-column mr-5">
                                        <a href="#" class="h3 text-dark text-hover-primary mb-3 mt-5">
                                        محافظة     {{$city->name}}
                                        </a>
                                    </div>
                                    <div class="ml-6 ml-lg-0 ml-xxl-6 flex-shrink-0">
                                        <form action="{{route('dashboard.login.cities.save')}}" method="post"
                                              type="post">
                                            @csrf
                                            <input type="hidden" name="city_id"
                                                   value="{{$city->id}}">
                                            <button type="submit"
                                                    class="btn font-weight-bolder text-uppercase btn-primary py-4 px-6">
                                                @lang('dashboard.open_city')
                                            </button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    @endforeach
                </div>
            @elseif(empty($cities->first()) && auth()->user()->doctor_type === 'owner')))
                <div class="row">
                    <div class="col-md-4"></div>
                    <div class="col-md-5">
                        <div class="card">
                            <div class="card-body" style="margin: 0 auto !important;">
                                <div class="symbol symbol-150 symbol-2by3 flex-shrink-0">
                                    <div class="symbol-label"
                                         style="width:330px; height: 250px; background-image: url({{asset('dashboard/assets/media/organization/default.png')}}">
                                    </div>
                                </div>
                                <div
                                    class="d-flex align-items-center justify-content-between p-4 flex-lg-wrap flex-xl-nowrap">
                                    <div class="d-flex flex-column mr-5">
                                        <div class="ml-6 ml-lg-0 ml-xxl-6 flex-shrink-0">

                                            <form action="{{route('dashboard.login.organization.save')}}" method="post"
                                                  type="post">
                                                @csrf
                                                <input type="hidden" name="city_id" value="">
                                                <a href="{{route('dashboard.login.organization.create')}}" type="submit"
                                                        class="btn font-weight-bolder text-uppercase btn-primary py-4 px-6"
                                                        style="
                                                            margin-right: 7%;
                                                            width: 240px;
                                                            padding: 6% !important;
                                                            font-size: 16px;
                                                        ">
                                                    <i class="ki ki-plus icon-nm"></i>
                                                    @lang('dashboard.create_organization')
                                                </a>
                                                <br>
                                                <br>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            @else
                <div class="row">
                    <div class="col-md-4"></div>
                    <div class="col-md-5">
                        <div class="card">
                            <div class="card-body" style="margin: 0 auto !important;">
                                <div class="symbol symbol-150 symbol-2by3 flex-shrink-0">
                                    <div class="symbol-label"
                                         style="width:330px; height: 250px; background-image: url({{asset('dashboard/assets/media/organization/default.png')}}">
                                    </div>
                                </div>
                                <div
                                    class="d-flex align-items-center justify-content-between p-4 flex-lg-wrap flex-xl-nowrap">
                                    <div class="d-flex flex-column mr-5">

                                        <div class="ml-6 ml-lg-0 ml-xxl-6 flex-shrink-0">
                                            <h1 style="margin: 10px 0px 25px; font-size: 30px">@lang('dashboard.no_organization_available') </h1>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            @endif
            </div>
        </div>
    </div>
@endsection

resources/views/dashboard/index.blade.php
@extends('dashboard.layouts.app')
@push('style')
    <link href="{{asset('dashboard/assets/css/pages/login/login-4.css')}}" rel="stylesheet" type="text/css"/>
@endpush
@section('page')
    <div class="d-flex flex-column-fluid">
        <div class="container">
            <a href="{{route('dashboard.logout')}}" type="submit"
               class="btn font-weight-bolder text-uppercase btn-danger py-4 px-6"
               style="float: left;margin-top: 22px;">
                <i class="flaticon-logout"></i>
                @lang('dashboard.logout')
            </a>
            &nbsp; &nbsp;
            <a href="{{route('dashboard.login.organization.index')}}" type="submit"
               class="btn font-weight-bolder text-uppercase btn-primary py-4 px-6"
               style="float: left;margin-top: 22px;  margin-left: 8px">
                <i class="flaticon-logout"></i>
                @lang('dashboard.back')
            </a>
            <div  style="margin: 11% auto;">

                    <div class="row" style=" margin-top: 4% !important;">
                        @if(session()->has('status'))
                            @include('dashboard.includes.alerts',['message' => session()->get('message'),'alert_class' => session()->get('status')])
                        @endif
                        @foreach($beds as $bed)
                            <div class="col-md-4" style="margin-bottom: 3%">
                                <div class="card card-custom">
                                    <div class="card-body row">
                                        <div class="col-md-6">
                                            <div class="symbol symbol-150 symbol-2by3 flex-shrink-0">
                                                <i style="font-size: 120px; color: #0d8ddc" class="fa fa-bed"></i>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            @if($bed->type == 'full')
                                                <button type="button" class="btn btn-danger font-weight-bold mr-2 btn-lg">
                                                   مشغول
                                                </button>
                                                <div>
                                                    <br>
                                                    <span>اسم المريض: <strong>مريض تحريبى</strong> </span><br>
                                                    <span>تاريخ الدخول: <strong>15/12/2020</strong></span>
                                                </div>
                                            @else
                                                <button type="button" class="btn btn-success font-weight-bold mr-2 btn-lg">
                                                    متاح
                                                </button>
                                                <div>
                                                    <br>
                                                    <span>اسم المريض: <strong> </strong> </span><br>
                                                    <span>تاريخ الدخول: <strong></strong></span>
                                                </div>
                                            @endif


                                        </div>
                                    </div>
                                </div>
                            </div>
                        @endforeach
                    </div>
            </div>
        </div>
    </div>
@endsection

resources/views/dashboard/login.blade.php
@extends('dashboard.layouts.app')
@push('style')
    <link href="{{asset('dashboard/assets/css/pages/login/login-4.css')}}" rel="stylesheet" type="text/css"/>
    <style>
        @media (min-width: 992px){
            .login.login-4 .login-aside .login-conteiner {
                min-height: 660px !important;
                background-size: cover !important;
                background-position: center;
                background-repeat: no-repeat;
            }
            .bgi-position-y-bottom {
                background-position-y:  no-repeat;
            }
            .bgi-no-repeat {
                background-repeat: no-repeat;
            }
        }
    </style>
@endpush
@section('page')
    <div class="login login-4 wizard d-flex flex-column flex-lg-row flex-column-fluid">
        <!--begin::Content-->
        <div
            class="login-container order-2 order-lg-1 d-flex flex-center flex-row-fluid px-7 pt-lg-0 pb-lg-0 pt-4 pb-6 bg-white">
            <!--begin::Wrapper-->
            <div class="login-content d-flex flex-column pt-lg-0 pt-12">
                <!--begin::Logo-->
                <a href="#" class="login-logo pb-xl-20 pb-15">
                    <img src="{{asset('dashboard/assets/media/organization/logo.png')}}" class="max-h-100px" alt=""/>
                </a>
                <!--end::Logo-->
                <!--begin::Signin-->
                <div class="login-form">
                    <!--begin::Form-->
                    <form class="form" action="{{route('dashboard.login_post')}}" method="post">
                    @csrf

                        <div class="pb-5 pb-lg-15">
                            <h3 class="font-weight-bolder text-dark font-size-h2 font-size-h1-lg">@lang('dashboard.sign_in')</h3>
                        </div>

                        <div class="form-group">
                            <label class="font-size-h6 font-weight-bolder text-dark">@lang('dashboard.mobile')</label>
                            <input class="form-control form-control-solid h-auto py-7 px-6 rounded-lg border-0  {{ $errors->has('mobile') ? 'is-invalid' : '' }}"
                                   type="number" min=0  value="{{ old('mobile')}}" name="mobile" autocomplete="off"/>
                            <div class="invalid-feedback" style="padding-right: 0"><strong>{{ $errors->has('mobile') ? $errors->first('mobile') : '' }}</strong></div>
                        </div>

                        <div class="form-group">
                            <div class="d-flex justify-content-between mt-n5">
                                <label
                                    class="font-size-h6 font-weight-bolder text-dark pt-5">@lang('dashboard.password')</label>
                            </div>
                            <input class="form-control form-control-solid h-auto py-7 px-6 rounded-lg border-0  {{ $errors->has('password') ? 'is-invalid' : '' }}"
                                   type="password" value="{{ old('password')}}" name="password" autocomplete="off"/>
                            <div class="invalid-feedback" style="padding-right: 0"><strong>{{ $errors->has('password') ? $errors->first('password') : '' }}</strong></div>

                        </div>

                        <div class="pb-lg-0 pb-5">
                            <button type="submit"
                                    class="btn btn-primary font-weight-bolder font-size-h6 px-8 py-4 my-3 mr-3">@lang('dashboard.sign_in')
                            </button>
                        </div>
                    </form>

                </div>
            </div>
        </div>
        <!--begin::Content-->
        <!--begin::Aside-->
        <div class="login-aside order-1 order-lg-2 bgi-no-repeat bgi-position-x-right">
            <div class="login-conteiner bgi-no-repeat bgi-position-x-right bgi-position-y-bottom"
                 style="background-image: url({{asset('dashboard/assets/media/svg/illustrations/login-visual-1.svg')}});">
                <!--begin::Aside title-->
                <a href="#" class="login-logo">
                    <img src="{{asset('dashboard/assets/media/organization/hosibtal.png')}}" style="position: absolute;
                        width: 8%;
                        top: 0%;
                        left: 0%;" alt=""/>
                </a>
                <!--end::Aside title-->
            </div>
        </div>
        <!--end::Aside-->
    </div>
@endsection

resources/views/dashboard/organizations.blade.php
@extends('dashboard.layouts.app')
@push('style')
    <link href="{{asset('dashboard/assets/css/pages/login/login-4.css')}}" rel="stylesheet" type="text/css"/>
@endpush
@section('page')
    <div class="d-flex flex-column-fluid">
        <div class="container">
            <a href="{{route('dashboard.logout')}}" type="submit"
               class="btn font-weight-bolder text-uppercase btn-danger py-4 px-6"
               style="float: left;margin-top: 22px;">
                <i class="flaticon-logout"></i>
                @lang('dashboard.logout')
            </a>
            <a href="{{route('dashboard.login.cities.index')}}" type="submit"
               class="btn font-weight-bolder text-uppercase btn-primary py-4 px-6"
               style="float: left;margin-top: 22px; margin-left: 5px">
                <i class="flaticon-logout"></i>
                @lang('dashboard.back')
            </a>
        <div  style="margin: 11% auto;">

                <div class="row" style=" @if($organizations->count() < 4) margin-top: 17% !important; @else margin-top: 4% !important; @endif">
                    @if(session()->has('status'))
                        @include('dashboard.includes.alerts',['message' => session()->get('message'),'alert_class' => session()->get('status')])
                    @endif
                    @foreach($organizations as $organization)
                        <div class="col-md-4" style="margin-bottom: 3%">
                            <div class="card card-custom">
                                <div class="card-body ">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="symbol symbol-120 symbol-2by3 flex-shrink-0">
                                                <div class="symbol-label" style="background-image: url({{ asset('dashboard/assets/media/organization/default.png')}})"></div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div style="font-size: 14px !important;">
                                                <button type="button" class="btn btn-success font-weight-bold mr-1 mb-1 btn-sm">
                                                    <span>عدد السراير الكلى: <strong>{{$organization->number_beds_total}}</strong><br></span>
                                                </button>
                                                <button type="button" class="btn btn-success font-weight-bold mr-1 mb-1 btn-sm">
                                                  السراير المتاحة : <strong>{{$organization->number_beds_avaible}}</strong><br>
                                                </button>
                                               <button type="button" class="btn btn-danger font-weight-bold mr-1 mb-1 btn-sm">
                                                    السراير المشغولة : <strong>{{$organization->number_beds_pending}}</strong>
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                    <div
                                        class="d-flex align-items-center justify-content-between p-4 flex-lg-wrap flex-xl-nowrap">
                                        <div class="d-flex flex-column mr-5">
                                            <a href="#" style="font-size: 15px !important;" class="h3 text-dark text-hover-primary mb-3 mt-5">
                                                {{$organization->name}}
                                            </a>
                                        </div>
                                        <div class="ml-6 ml-lg-0 ml-xxl-6 flex-shrink-0">
                                            <form action="{{route('dashboard.login.organization.save')}}" method="post"
                                                  type="post">
                                                @csrf
                                                <input type="hidden" name="organization_id"
                                                       value="{{$organization->id}}">
                                                <button type="submit"
                                                        class="btn font-weight-bolder text-uppercase btn-primary py-4 px-6">
                                                    @lang('dashboard.open_organization')
                                                </button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    @endforeach
                    <div class="col-md-4" style="margin-bottom: 3%">
                        <div class="card card-custom">
                            <div class="card-body">
                                <div class="symbol symbol-120 symbol-2by3 flex-shrink-0">
                                    <div class="symbol-label" style="background-image: url({{ asset('dashboard/assets/media/organization/default.png')}});
                                        margin: 0 50%;"></div>
                                </div>
                                <div class="d-flex align-items-center justify-content-between p-4 flex-lg-wrap flex-xl-nowrap">

                                    <div class="ml-6 ml-lg-0 ml-xxl-6 flex-shrink-0">
                                        <form action="{{route('dashboard.login.organization.save')}}" method="post"
                                              type="post">
                                            @csrf
                                            <input type="hidden" name="organization_id" value="">
                                            <a href="{{route('dashboard.login.organization.create')}}" type="submit"
                                               class="btn font-weight-bolder text-uppercase btn-primary py-4 px-6 "
                                               style="margin-right: 50px !important;">
                                                <i class="ki ki-plus icon-nm"></i>
                                                @lang('dashboard.create_organization')
                                            </a>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection